2016-10-30 21:58:59,124 [Thread-8:19976] [django.request:256] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /
Traceback (most recent call last):
  File "D:\software\Python\lib\site-packages\django-1.8.13-py2.7.egg\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\Temp\blog_project\blog\views.py", line 19, in index
    return render(request, 'index.html', locals())
  File "D:\software\Python\lib\site-packages\django-1.8.13-py2.7.egg\django\shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "D:\software\Python\lib\site-packages\django-1.8.13-py2.7.egg\django\template\loader.py", line 98, in render_to_string
    template = get_template(template_name, using=using)
  File "D:\software\Python\lib\site-packages\django-1.8.13-py2.7.egg\django\template\loader.py", line 35, in get_template
    return engine.get_template(template_name, dirs)
  File "D:\software\Python\lib\site-packages\django-1.8.13-py2.7.egg\django\template\backends\django.py", line 30, in get_template
    return Template(self.engine.get_template(template_name, dirs))
  File "D:\software\Python\lib\site-packages\django-1.8.13-py2.7.egg\django\template\engine.py", line 167, in get_template
    template, origin = self.find_template(template_name, dirs)
  File "D:\software\Python\lib\site-packages\django-1.8.13-py2.7.egg\django\template\engine.py", line 141, in find_template
    source, display_name = loader(name, dirs)
  File "D:\software\Python\lib\site-packages\django-1.8.13-py2.7.egg\django\template\loaders\base.py", line 13, in __call__
    return self.load_template(template_name, template_dirs)
  File "D:\software\Python\lib\site-packages\django-1.8.13-py2.7.egg\django\template\loaders\base.py", line 23, in load_template
    template = Template(source, origin, template_name, self.engine)
  File "D:\software\Python\lib\site-packages\django-1.8.13-py2.7.egg\django\template\base.py", line 191, in __init__
    self.nodelist = engine.compile_string(template_string, origin)
  File "D:\software\Python\lib\site-packages\django-1.8.13-py2.7.egg\django\template\engine.py", line 261, in compile_string
    return parser.parse()
  File "D:\software\Python\lib\site-packages\django-1.8.13-py2.7.egg\django\template\base.py", line 340, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "D:\software\Python\lib\site-packages\django-1.8.13-py2.7.egg\django\template\base.py", line 396, in invalid_block_tag
    raise self.error(token, "Invalid block tag: '%s'" % command)
TemplateSyntaxError: Invalid block tag: 'SITE_NAME'
2016-10-30 21:59:21,447 [Thread-2:20160] [django.request:256] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /
Traceback (most recent call last):
  File "D:\software\Python\lib\site-packages\django-1.8.13-py2.7.egg\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\Temp\blog_project\blog\views.py", line 19, in index
    return render(request, 'index.html', locals())
  File "D:\software\Python\lib\site-packages\django-1.8.13-py2.7.egg\django\shortcuts.py", line 67, in render
    template_name, context, request=request, using=using)
  File "D:\software\Python\lib\site-packages\django-1.8.13-py2.7.egg\django\template\loader.py", line 98, in render_to_string
    template = get_template(template_name, using=using)
  File "D:\software\Python\lib\site-packages\django-1.8.13-py2.7.egg\django\template\loader.py", line 35, in get_template
    return engine.get_template(template_name, dirs)
  File "D:\software\Python\lib\site-packages\django-1.8.13-py2.7.egg\django\template\backends\django.py", line 30, in get_template
    return Template(self.engine.get_template(template_name, dirs))
  File "D:\software\Python\lib\site-packages\django-1.8.13-py2.7.egg\django\template\engine.py", line 167, in get_template
    template, origin = self.find_template(template_name, dirs)
  File "D:\software\Python\lib\site-packages\django-1.8.13-py2.7.egg\django\template\engine.py", line 141, in find_template
    source, display_name = loader(name, dirs)
  File "D:\software\Python\lib\site-packages\django-1.8.13-py2.7.egg\django\template\loaders\base.py", line 13, in __call__
    return self.load_template(template_name, template_dirs)
  File "D:\software\Python\lib\site-packages\django-1.8.13-py2.7.egg\django\template\loaders\base.py", line 23, in load_template
    template = Template(source, origin, template_name, self.engine)
  File "D:\software\Python\lib\site-packages\django-1.8.13-py2.7.egg\django\template\base.py", line 191, in __init__
    self.nodelist = engine.compile_string(template_string, origin)
  File "D:\software\Python\lib\site-packages\django-1.8.13-py2.7.egg\django\template\engine.py", line 261, in compile_string
    return parser.parse()
  File "D:\software\Python\lib\site-packages\django-1.8.13-py2.7.egg\django\template\base.py", line 340, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "D:\software\Python\lib\site-packages\django-1.8.13-py2.7.egg\django\template\base.py", line 396, in invalid_block_tag
    raise self.error(token, "Invalid block tag: '%s'" % command)
TemplateSyntaxError: Invalid block tag: 'SITE_NAME'
2016-10-31 23:16:28,079 [Thread-16:5988] [django.request:170] [base:get_response] [WARNING]- Not Found: /favicon.ico
2016-11-02 22:50:27,140 [Thread-10:3328] [django.request:170] [base:get_response] [WARNING]- Not Found: /favicon.ico
2016-11-02 23:12:26,517 [Thread-29:20628] [django.request:170] [base:get_response] [WARNING]- Not Found: /admin/blog/article/1/index.js.map/
2016-11-02 23:12:59,796 [Thread-48:4948] [django.request:170] [base:get_response] [WARNING]- Not Found: /admin/blog/article/1/index.js.map/
2016-11-02 23:15:04,821 [Thread-72:19416] [django.request:170] [base:get_response] [WARNING]- Not Found: /admin/blog/article/1/index.js.map/
2016-11-02 23:15:30,717 [Thread-91:19060] [django.request:170] [base:get_response] [WARNING]- Not Found: /admin/blog/article/1/index.js.map/
2016-11-02 23:18:40,849 [Thread-101:20460] [django.request:170] [base:get_response] [WARNING]- Not Found: /admin/blog/article/index.js.map/
2016-11-02 23:18:43,984 [Thread-103:22436] [django.request:170] [base:get_response] [WARNING]- Not Found: /admin/blog/index.js.map
2016-11-02 23:18:48,318 [Thread-107:11188] [django.request:170] [base:get_response] [WARNING]- Not Found: /admin/blog/article/add/index.js.map/
2016-11-02 23:19:46,552 [Thread-127:21924] [django.request:170] [base:get_response] [WARNING]- Not Found: /admin/blog/article/add/index.js.map/
2016-11-02 23:37:39,668 [Thread-2:18072] [django.request:256] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /admin/blog/
Traceback (most recent call last):
  File "D:\software\Python\lib\site-packages\django-1.8.13-py2.7.egg\django\core\handlers\base.py", line 119, in get_response
    resolver_match = resolver.resolve(request.path_info)
  File "D:\software\Python\lib\site-packages\django-1.8.13-py2.7.egg\django\core\urlresolvers.py", line 365, in resolve
    for pattern in self.url_patterns:
  File "D:\software\Python\lib\site-packages\django-1.8.13-py2.7.egg\django\core\urlresolvers.py", line 401, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "D:\software\Python\lib\site-packages\django-1.8.13-py2.7.egg\django\core\urlresolvers.py", line 395, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "D:\software\Python\lib\importlib\__init__.py", line 37, in import_module
    __import__(name)
  File "E:\Temp\blog_project\blog_project\urls.py", line 23
SyntaxError: Non-ASCII character '\xe8' in file E:\Temp\blog_project\blog_project\urls.py on line 23, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
2016-11-02 23:37:57,265 [Thread-3:21716] [django.request:256] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /admin/blog/
Traceback (most recent call last):
  File "D:\software\Python\lib\site-packages\django-1.8.13-py2.7.egg\django\core\handlers\base.py", line 164, in get_response
    response = response.render()
  File "D:\software\Python\lib\site-packages\django-1.8.13-py2.7.egg\django\template\response.py", line 158, in render
    self.content = self.rendered_content
  File "D:\software\Python\lib\site-packages\django-1.8.13-py2.7.egg\django\template\response.py", line 135, in rendered_content
    content = template.render(context, self._request)
  File "D:\software\Python\lib\site-packages\django-1.8.13-py2.7.egg\django\template\backends\django.py", line 74, in render
    return self.template.render(context)
  File "D:\software\Python\lib\site-packages\django-1.8.13-py2.7.egg\django\template\base.py", line 210, in render
    return self._render(context)
  File "D:\software\Python\lib\site-packages\django-1.8.13-py2.7.egg\django\template\base.py", line 202, in _render
    return self.nodelist.render(context)
  File "D:\software\Python\lib\site-packages\django-1.8.13-py2.7.egg\django\template\base.py", line 905, in render
    bit = self.render_node(node, context)
  File "D:\software\Python\lib\site-packages\django-1.8.13-py2.7.egg\django\template\debug.py", line 79, in render_node
    return node.render(context)
  File "D:\software\Python\lib\site-packages\django-1.8.13-py2.7.egg\django\template\loader_tags.py", line 135, in render
    return compiled_parent._render(context)
  File "D:\software\Python\lib\site-packages\django-1.8.13-py2.7.egg\django\template\base.py", line 202, in _render
    return self.nodelist.render(context)
  File "D:\software\Python\lib\site-packages\django-1.8.13-py2.7.egg\django\template\base.py", line 905, in render
    bit = self.render_node(node, context)
  File "D:\software\Python\lib\site-packages\django-1.8.13-py2.7.egg\django\template\debug.py", line 79, in render_node
    return node.render(context)
  File "D:\software\Python\lib\site-packages\django-1.8.13-py2.7.egg\django\template\loader_tags.py", line 135, in render
    return compiled_parent._render(context)
  File "D:\software\Python\lib\site-packages\django-1.8.13-py2.7.egg\django\template\base.py", line 202, in _render
    return self.nodelist.render(context)
  File "D:\software\Python\lib\site-packages\django-1.8.13-py2.7.egg\django\template\base.py", line 905, in render
    bit = self.render_node(node, context)
  File "D:\software\Python\lib\site-packages\django-1.8.13-py2.7.egg\django\template\debug.py", line 79, in render_node
    return node.render(context)
  File "D:\software\Python\lib\site-packages\django-1.8.13-py2.7.egg\django\template\loader_tags.py", line 135, in render
    return compiled_parent._render(context)
  File "D:\software\Python\lib\site-packages\django-1.8.13-py2.7.egg\django\template\base.py", line 202, in _render
    return self.nodelist.render(context)
  File "D:\software\Python\lib\site-packages\django-1.8.13-py2.7.egg\django\template\base.py", line 905, in render
    bit = self.render_node(node, context)
  File "D:\software\Python\lib\site-packages\django-1.8.13-py2.7.egg\django\template\debug.py", line 79, in render_node
    return node.render(context)
  File "D:\software\Python\lib\site-packages\django-1.8.13-py2.7.egg\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "D:\software\Python\lib\site-packages\django-1.8.13-py2.7.egg\django\template\base.py", line 905, in render
    bit = self.render_node(node, context)
  File "D:\software\Python\lib\site-packages\django-1.8.13-py2.7.egg\django\template\debug.py", line 79, in render_node
    return node.render(context)
  File "D:\software\Python\lib\site-packages\django-1.8.13-py2.7.egg\django\template\base.py", line 1197, in render
    return func(*resolved_args, **resolved_kwargs)
  File "D:\software\Python\lib\site-packages\django-1.8.13-py2.7.egg\django\contrib\admin\templatetags\admin_static.py", line 17, in static
    return _static(path)
  File "D:\software\Python\lib\site-packages\django-1.8.13-py2.7.egg\django\contrib\staticfiles\templatetags\staticfiles.py", line 9, in static
    return staticfiles_storage.url(path)
  File "D:\software\Python\lib\site-packages\django-1.8.13-py2.7.egg\django\utils\functional.py", line 225, in inner
    self._setup()
  File "D:\software\Python\lib\site-packages\django-1.8.13-py2.7.egg\django\contrib\staticfiles\storage.py", line 394, in _setup
    self._wrapped = get_storage_class(settings.STATICFILES_STORAGE)()
  File "D:\software\Python\lib\site-packages\django-1.8.13-py2.7.egg\django\contrib\staticfiles\storage.py", line 39, in __init__
    *args, **kwargs)
  File "D:\software\Python\lib\site-packages\django-1.8.13-py2.7.egg\django\core\files\storage.py", line 185, in __init__
    self.location = abspathu(self.base_location)
  File "D:\software\Python\lib\ntpath.py", line 488, in abspath
    path = _getfullpathname(path)
TypeError: coercing to Unicode: need string or buffer, tuple found
2016-11-02 23:38:07,250 [Thread-2:20952] [django.request:256] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /admin/blog/
Traceback (most recent call last):
  File "D:\software\Python\lib\site-packages\django-1.8.13-py2.7.egg\django\core\handlers\base.py", line 164, in get_response
    response = response.render()
  File "D:\software\Python\lib\site-packages\django-1.8.13-py2.7.egg\django\template\response.py", line 158, in render
    self.content = self.rendered_content
  File "D:\software\Python\lib\site-packages\django-1.8.13-py2.7.egg\django\template\response.py", line 135, in rendered_content
    content = template.render(context, self._request)
  File "D:\software\Python\lib\site-packages\django-1.8.13-py2.7.egg\django\template\backends\django.py", line 74, in render
    return self.template.render(context)
  File "D:\software\Python\lib\site-packages\django-1.8.13-py2.7.egg\django\template\base.py", line 210, in render
    return self._render(context)
  File "D:\software\Python\lib\site-packages\django-1.8.13-py2.7.egg\django\template\base.py", line 202, in _render
    return self.nodelist.render(context)
  File "D:\software\Python\lib\site-packages\django-1.8.13-py2.7.egg\django\template\base.py", line 905, in render
    bit = self.render_node(node, context)
  File "D:\software\Python\lib\site-packages\django-1.8.13-py2.7.egg\django\template\debug.py", line 79, in render_node
    return node.render(context)
  File "D:\software\Python\lib\site-packages\django-1.8.13-py2.7.egg\django\template\loader_tags.py", line 135, in render
    return compiled_parent._render(context)
  File "D:\software\Python\lib\site-packages\django-1.8.13-py2.7.egg\django\template\base.py", line 202, in _render
    return self.nodelist.render(context)
  File "D:\software\Python\lib\site-packages\django-1.8.13-py2.7.egg\django\template\base.py", line 905, in render
    bit = self.render_node(node, context)
  File "D:\software\Python\lib\site-packages\django-1.8.13-py2.7.egg\django\template\debug.py", line 79, in render_node
    return node.render(context)
  File "D:\software\Python\lib\site-packages\django-1.8.13-py2.7.egg\django\template\loader_tags.py", line 135, in render
    return compiled_parent._render(context)
  File "D:\software\Python\lib\site-packages\django-1.8.13-py2.7.egg\django\template\base.py", line 202, in _render
    return self.nodelist.render(context)
  File "D:\software\Python\lib\site-packages\django-1.8.13-py2.7.egg\django\template\base.py", line 905, in render
    bit = self.render_node(node, context)
  File "D:\software\Python\lib\site-packages\django-1.8.13-py2.7.egg\django\template\debug.py", line 79, in render_node
    return node.render(context)
  File "D:\software\Python\lib\site-packages\django-1.8.13-py2.7.egg\django\template\loader_tags.py", line 135, in render
    return compiled_parent._render(context)
  File "D:\software\Python\lib\site-packages\django-1.8.13-py2.7.egg\django\template\base.py", line 202, in _render
    return self.nodelist.render(context)
  File "D:\software\Python\lib\site-packages\django-1.8.13-py2.7.egg\django\template\base.py", line 905, in render
    bit = self.render_node(node, context)
  File "D:\software\Python\lib\site-packages\django-1.8.13-py2.7.egg\django\template\debug.py", line 79, in render_node
    return node.render(context)
  File "D:\software\Python\lib\site-packages\django-1.8.13-py2.7.egg\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "D:\software\Python\lib\site-packages\django-1.8.13-py2.7.egg\django\template\base.py", line 905, in render
    bit = self.render_node(node, context)
  File "D:\software\Python\lib\site-packages\django-1.8.13-py2.7.egg\django\template\debug.py", line 79, in render_node
    return node.render(context)
  File "D:\software\Python\lib\site-packages\django-1.8.13-py2.7.egg\django\template\base.py", line 1197, in render
    return func(*resolved_args, **resolved_kwargs)
  File "D:\software\Python\lib\site-packages\django-1.8.13-py2.7.egg\django\contrib\admin\templatetags\admin_static.py", line 17, in static
    return _static(path)
  File "D:\software\Python\lib\site-packages\django-1.8.13-py2.7.egg\django\contrib\staticfiles\templatetags\staticfiles.py", line 9, in static
    return staticfiles_storage.url(path)
  File "D:\software\Python\lib\site-packages\django-1.8.13-py2.7.egg\django\utils\functional.py", line 225, in inner
    self._setup()
  File "D:\software\Python\lib\site-packages\django-1.8.13-py2.7.egg\django\contrib\staticfiles\storage.py", line 394, in _setup
    self._wrapped = get_storage_class(settings.STATICFILES_STORAGE)()
  File "D:\software\Python\lib\site-packages\django-1.8.13-py2.7.egg\django\contrib\staticfiles\storage.py", line 39, in __init__
    *args, **kwargs)
  File "D:\software\Python\lib\site-packages\django-1.8.13-py2.7.egg\django\core\files\storage.py", line 185, in __init__
    self.location = abspathu(self.base_location)
  File "D:\software\Python\lib\ntpath.py", line 488, in abspath
    path = _getfullpathname(path)
TypeError: coercing to Unicode: need string or buffer, tuple found
2016-11-02 23:38:34,029 [Thread-2:17732] [django.request:256] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /admin/blog/
Traceback (most recent call last):
  File "D:\software\Python\lib\site-packages\django-1.8.13-py2.7.egg\django\core\handlers\base.py", line 164, in get_response
    response = response.render()
  File "D:\software\Python\lib\site-packages\django-1.8.13-py2.7.egg\django\template\response.py", line 158, in render
    self.content = self.rendered_content
  File "D:\software\Python\lib\site-packages\django-1.8.13-py2.7.egg\django\template\response.py", line 135, in rendered_content
    content = template.render(context, self._request)
  File "D:\software\Python\lib\site-packages\django-1.8.13-py2.7.egg\django\template\backends\django.py", line 74, in render
    return self.template.render(context)
  File "D:\software\Python\lib\site-packages\django-1.8.13-py2.7.egg\django\template\base.py", line 210, in render
    return self._render(context)
  File "D:\software\Python\lib\site-packages\django-1.8.13-py2.7.egg\django\template\base.py", line 202, in _render
    return self.nodelist.render(context)
  File "D:\software\Python\lib\site-packages\django-1.8.13-py2.7.egg\django\template\base.py", line 905, in render
    bit = self.render_node(node, context)
  File "D:\software\Python\lib\site-packages\django-1.8.13-py2.7.egg\django\template\debug.py", line 79, in render_node
    return node.render(context)
  File "D:\software\Python\lib\site-packages\django-1.8.13-py2.7.egg\django\template\loader_tags.py", line 135, in render
    return compiled_parent._render(context)
  File "D:\software\Python\lib\site-packages\django-1.8.13-py2.7.egg\django\template\base.py", line 202, in _render
    return self.nodelist.render(context)
  File "D:\software\Python\lib\site-packages\django-1.8.13-py2.7.egg\django\template\base.py", line 905, in render
    bit = self.render_node(node, context)
  File "D:\software\Python\lib\site-packages\django-1.8.13-py2.7.egg\django\template\debug.py", line 79, in render_node
    return node.render(context)
  File "D:\software\Python\lib\site-packages\django-1.8.13-py2.7.egg\django\template\loader_tags.py", line 135, in render
    return compiled_parent._render(context)
  File "D:\software\Python\lib\site-packages\django-1.8.13-py2.7.egg\django\template\base.py", line 202, in _render
    return self.nodelist.render(context)
  File "D:\software\Python\lib\site-packages\django-1.8.13-py2.7.egg\django\template\base.py", line 905, in render
    bit = self.render_node(node, context)
  File "D:\software\Python\lib\site-packages\django-1.8.13-py2.7.egg\django\template\debug.py", line 79, in render_node
    return node.render(context)
  File "D:\software\Python\lib\site-packages\django-1.8.13-py2.7.egg\django\template\loader_tags.py", line 135, in render
    return compiled_parent._render(context)
  File "D:\software\Python\lib\site-packages\django-1.8.13-py2.7.egg\django\template\base.py", line 202, in _render
    return self.nodelist.render(context)
  File "D:\software\Python\lib\site-packages\django-1.8.13-py2.7.egg\django\template\base.py", line 905, in render
    bit = self.render_node(node, context)
  File "D:\software\Python\lib\site-packages\django-1.8.13-py2.7.egg\django\template\debug.py", line 79, in render_node
    return node.render(context)
  File "D:\software\Python\lib\site-packages\django-1.8.13-py2.7.egg\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "D:\software\Python\lib\site-packages\django-1.8.13-py2.7.egg\django\template\base.py", line 905, in render
    bit = self.render_node(node, context)
  File "D:\software\Python\lib\site-packages\django-1.8.13-py2.7.egg\django\template\debug.py", line 79, in render_node
    return node.render(context)
  File "D:\software\Python\lib\site-packages\django-1.8.13-py2.7.egg\django\template\base.py", line 1197, in render
    return func(*resolved_args, **resolved_kwargs)
  File "D:\software\Python\lib\site-packages\django-1.8.13-py2.7.egg\django\contrib\admin\templatetags\admin_static.py", line 17, in static
    return _static(path)
  File "D:\software\Python\lib\site-packages\django-1.8.13-py2.7.egg\django\contrib\staticfiles\templatetags\staticfiles.py", line 9, in static
    return staticfiles_storage.url(path)
  File "D:\software\Python\lib\site-packages\django-1.8.13-py2.7.egg\django\utils\functional.py", line 225, in inner
    self._setup()
  File "D:\software\Python\lib\site-packages\django-1.8.13-py2.7.egg\django\contrib\staticfiles\storage.py", line 394, in _setup
    self._wrapped = get_storage_class(settings.STATICFILES_STORAGE)()
  File "D:\software\Python\lib\site-packages\django-1.8.13-py2.7.egg\django\contrib\staticfiles\storage.py", line 39, in __init__
    *args, **kwargs)
  File "D:\software\Python\lib\site-packages\django-1.8.13-py2.7.egg\django\core\files\storage.py", line 185, in __init__
    self.location = abspathu(self.base_location)
  File "D:\software\Python\lib\ntpath.py", line 488, in abspath
    path = _getfullpathname(path)
TypeError: coercing to Unicode: need string or buffer, tuple found
2016-11-02 23:40:02,667 [Thread-2:18048] [django.request:256] [base:handle_uncaught_exception] [ERROR]- Internal Server Error: /admin/blog/
Traceback (most recent call last):
  File "D:\software\Python\lib\site-packages\django-1.8.13-py2.7.egg\django\core\handlers\base.py", line 164, in get_response
    response = response.render()
  File "D:\software\Python\lib\site-packages\django-1.8.13-py2.7.egg\django\template\response.py", line 158, in render
    self.content = self.rendered_content
  File "D:\software\Python\lib\site-packages\django-1.8.13-py2.7.egg\django\template\response.py", line 135, in rendered_content
    content = template.render(context, self._request)
  File "D:\software\Python\lib\site-packages\django-1.8.13-py2.7.egg\django\template\backends\django.py", line 74, in render
    return self.template.render(context)
  File "D:\software\Python\lib\site-packages\django-1.8.13-py2.7.egg\django\template\base.py", line 210, in render
    return self._render(context)
  File "D:\software\Python\lib\site-packages\django-1.8.13-py2.7.egg\django\template\base.py", line 202, in _render
    return self.nodelist.render(context)
  File "D:\software\Python\lib\site-packages\django-1.8.13-py2.7.egg\django\template\base.py", line 905, in render
    bit = self.render_node(node, context)
  File "D:\software\Python\lib\site-packages\django-1.8.13-py2.7.egg\django\template\debug.py", line 79, in render_node
    return node.render(context)
  File "D:\software\Python\lib\site-packages\django-1.8.13-py2.7.egg\django\template\loader_tags.py", line 135, in render
    return compiled_parent._render(context)
  File "D:\software\Python\lib\site-packages\django-1.8.13-py2.7.egg\django\template\base.py", line 202, in _render
    return self.nodelist.render(context)
  File "D:\software\Python\lib\site-packages\django-1.8.13-py2.7.egg\django\template\base.py", line 905, in render
    bit = self.render_node(node, context)
  File "D:\software\Python\lib\site-packages\django-1.8.13-py2.7.egg\django\template\debug.py", line 79, in render_node
    return node.render(context)
  File "D:\software\Python\lib\site-packages\django-1.8.13-py2.7.egg\django\template\loader_tags.py", line 135, in render
    return compiled_parent._render(context)
  File "D:\software\Python\lib\site-packages\django-1.8.13-py2.7.egg\django\template\base.py", line 202, in _render
    return self.nodelist.render(context)
  File "D:\software\Python\lib\site-packages\django-1.8.13-py2.7.egg\django\template\base.py", line 905, in render
    bit = self.render_node(node, context)
  File "D:\software\Python\lib\site-packages\django-1.8.13-py2.7.egg\django\template\debug.py", line 79, in render_node
    return node.render(context)
  File "D:\software\Python\lib\site-packages\django-1.8.13-py2.7.egg\django\template\loader_tags.py", line 135, in render
    return compiled_parent._render(context)
  File "D:\software\Python\lib\site-packages\django-1.8.13-py2.7.egg\django\template\base.py", line 202, in _render
    return self.nodelist.render(context)
  File "D:\software\Python\lib\site-packages\django-1.8.13-py2.7.egg\django\template\base.py", line 905, in render
    bit = self.render_node(node, context)
  File "D:\software\Python\lib\site-packages\django-1.8.13-py2.7.egg\django\template\debug.py", line 79, in render_node
    return node.render(context)
  File "D:\software\Python\lib\site-packages\django-1.8.13-py2.7.egg\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "D:\software\Python\lib\site-packages\django-1.8.13-py2.7.egg\django\template\base.py", line 905, in render
    bit = self.render_node(node, context)
  File "D:\software\Python\lib\site-packages\django-1.8.13-py2.7.egg\django\template\debug.py", line 79, in render_node
    return node.render(context)
  File "D:\software\Python\lib\site-packages\django-1.8.13-py2.7.egg\django\template\base.py", line 1197, in render
    return func(*resolved_args, **resolved_kwargs)
  File "D:\software\Python\lib\site-packages\django-1.8.13-py2.7.egg\django\contrib\admin\templatetags\admin_static.py", line 17, in static
    return _static(path)
  File "D:\software\Python\lib\site-packages\django-1.8.13-py2.7.egg\django\contrib\staticfiles\templatetags\staticfiles.py", line 9, in static
    return staticfiles_storage.url(path)
  File "D:\software\Python\lib\site-packages\django-1.8.13-py2.7.egg\django\utils\functional.py", line 225, in inner
    self._setup()
  File "D:\software\Python\lib\site-packages\django-1.8.13-py2.7.egg\django\contrib\staticfiles\storage.py", line 394, in _setup
    self._wrapped = get_storage_class(settings.STATICFILES_STORAGE)()
  File "D:\software\Python\lib\site-packages\django-1.8.13-py2.7.egg\django\contrib\staticfiles\storage.py", line 39, in __init__
    *args, **kwargs)
  File "D:\software\Python\lib\site-packages\django-1.8.13-py2.7.egg\django\core\files\storage.py", line 185, in __init__
    self.location = abspathu(self.base_location)
  File "D:\software\Python\lib\ntpath.py", line 488, in abspath
    path = _getfullpathname(path)
TypeError: coercing to Unicode: need string or buffer, tuple found
